apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  labels:
    name: data-pvc
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage