volumes:
  my-vol:

networks:
  my-net:

services: 
  my-db:
    image: stackupiss/northwind-db:v1
    volumes:
    - my-vol:/var/lib/mysql
    networks:
    - my-net
  my-app:
    image: stackupiss/northwind-app:v1
    ports:
    - 8080-9000:3000
    environment:
    - DB_HOST=my-db
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - my-net

