---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_HOST: mydb-cluster-mysql-master.mywp.svc.cluster.local
  WORDPRESS_DB_NAME: mywpdb
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
data:
#  MYSQL_ROOT_PASSWORD: cm9vdHJvb3Q=
  ROOT_PASSWORD: cm9vdHJvb3Q=  
  WORDPRESS_DB_PASSWORD: cm9vdHJvb3Q=
   